### ISSUE TITLE
Upgrade rails development dependency

### ISSUE THREAD

**Issue by yashupadhyay16** [amalagaura/camunda-workflow#63]
We are trying to upgrade rails version from 6 to 7, camunda stopped working, because of dependency.

**Comment by amalagaura** [comment]
@yashupadhyay16  Sorry I have been neglecting this gem and I didn't see your issue that you created. 

I had updated the dependencies, but not the development dependencoes for Rails 7. I am going to work now to update the Her dependencies as well. 

I am also going to remove the Gemfile.lock because I don't think it is so necessary.

**Comment by yashupadhyay16** [comment]
No Issue, yup her is also on his new version now.
Thanks for that :+1:

**Comment by yashupadhyay16** [comment]
@amalagaura Here is my MR for the dependency if you can please approve and merge this.
https://github.com/amalagaura/camunda-workflow/pull/64

**Comment by amalagaura** [comment]
Closed via #71
